# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            "Ian Whitehouse"
tagline:          ""
description:      "CS student (AU '24) and simulator game enthusiast.  Interested in autonomous agents and human-machine teaming"
url:              "https://iwhitehouse.us"
baseurl:          ""

author:
  name:           "Ian Whitehouse"
  URL:            "iw9892a@american.edu"

paginate:         5

# Custom vars
# version:          2.1.0

# github:
#   repo:           https://github.com/ianjwhitehouse/ianjwhitehouse.github.io
