# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Ian Whitehouse
tagline:          "Computer Science Student and Researcher"
description:      "Welcome to my profile.  I am a computer science student at American University, graduating in Spring 2024.  Please take a look at some of the work I did during my time at American"
url:              https://iwhitehouse.us
baseurl:          /

author:
  name:           "Ian Whitehouse"
  URL:            "iw9892a@american.edu"

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ianjwhitehouse/ianjwhitehouse.github.io
