# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            "Ian Whitehouse"
tagline:          ""
description:      ""
url:              "https://iwhitehouse.us"
# baseurl:          "/"

author:
  name:           "Ian Whitehouse"
  URL:            "iw9892a@american.edu"

paginate:         5
# paginate_path: "/works/page:num/"

# Custom vars
# version:          2.1.0

# github:
#   repo:           https://github.com/ianjwhitehouse/ianjwhitehouse.github.io
